[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --gc --themesDir ../.. " 
  #command= """hugo \
  #      --source examplesSite \
  #--config exampleSite/config.toml \
  #--themesDir ../.. \
  #--theme repo"""
[build.environment]
  HUGO_VERSION = "0.60.1"
  HUGO_THEME = "repo"
